services:
  db:
    image: mysql:8.0
    container_name: mysql-projet
    restart: always
    environment:
      MYSQL_DATABASE: projet_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
